# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WereWolfModerator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'RealmSwift'
    pod 'SwiftyJSON'
    pod 'DynamicColor', '~> 4.0.1'
    pod 'Localize-Swift', '~> 2.0'




  target 'WereWolfModeratorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WereWolfModeratorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
